name: qiskit-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - ipykernel
  - qiskit
  - qiskit-aer
  - qiskit-ibm-runtime
  - matplotlib
  - numpy
  - scipy
  - qutip
  - pennylane>=0.36
  - autoray>=0.6.12
  - python-dotenv
  - nbconvert[webpdf]